//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.VentaBA.ServicioValidarLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HayErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonListaProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonValidarLoginEscritorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonVerificarPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObtenerEquiposAnwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObtenerGuiasDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlGuiaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaGuiaDespachoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaPerfilUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaSolicitudServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlListaStockProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPerfilUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlSolicitudServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlStockProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HayErrores {
            get {
                return this.HayErroresField;
            }
            set {
                if ((this.HayErroresField.Equals(value) != true)) {
                    this.HayErroresField = value;
                    this.RaisePropertyChanged("HayErrores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonListaProducto {
            get {
                return this.JsonListaProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonListaProductoField, value) != true)) {
                    this.JsonListaProductoField = value;
                    this.RaisePropertyChanged("JsonListaProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonProducto {
            get {
                return this.JsonProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonProductoField, value) != true)) {
                    this.JsonProductoField = value;
                    this.RaisePropertyChanged("JsonProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonValidarLoginEscritorio {
            get {
                return this.JsonValidarLoginEscritorioField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonValidarLoginEscritorioField, value) != true)) {
                    this.JsonValidarLoginEscritorioField = value;
                    this.RaisePropertyChanged("JsonValidarLoginEscritorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonVerificarPassword {
            get {
                return this.JsonVerificarPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonVerificarPasswordField, value) != true)) {
                    this.JsonVerificarPasswordField = value;
                    this.RaisePropertyChanged("JsonVerificarPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObtenerEquiposAnwo {
            get {
                return this.ObtenerEquiposAnwoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObtenerEquiposAnwoField, value) != true)) {
                    this.ObtenerEquiposAnwoField = value;
                    this.RaisePropertyChanged("ObtenerEquiposAnwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObtenerGuiasDespacho {
            get {
                return this.ObtenerGuiasDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObtenerGuiasDespachoField, value) != true)) {
                    this.ObtenerGuiasDespachoField = value;
                    this.RaisePropertyChanged("ObtenerGuiasDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlFactura {
            get {
                return this.XmlFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlFacturaField, value) != true)) {
                    this.XmlFacturaField = value;
                    this.RaisePropertyChanged("XmlFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlGuiaDespacho {
            get {
                return this.XmlGuiaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlGuiaDespachoField, value) != true)) {
                    this.XmlGuiaDespachoField = value;
                    this.RaisePropertyChanged("XmlGuiaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaFactura {
            get {
                return this.XmlListaFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaFacturaField, value) != true)) {
                    this.XmlListaFacturaField = value;
                    this.RaisePropertyChanged("XmlListaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaGuiaDespacho {
            get {
                return this.XmlListaGuiaDespachoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaGuiaDespachoField, value) != true)) {
                    this.XmlListaGuiaDespachoField = value;
                    this.RaisePropertyChanged("XmlListaGuiaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaPerfilUsuario {
            get {
                return this.XmlListaPerfilUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaPerfilUsuarioField, value) != true)) {
                    this.XmlListaPerfilUsuarioField = value;
                    this.RaisePropertyChanged("XmlListaPerfilUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaProducto {
            get {
                return this.XmlListaProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaProductoField, value) != true)) {
                    this.XmlListaProductoField = value;
                    this.RaisePropertyChanged("XmlListaProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaSolicitudServicio {
            get {
                return this.XmlListaSolicitudServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaSolicitudServicioField, value) != true)) {
                    this.XmlListaSolicitudServicioField = value;
                    this.RaisePropertyChanged("XmlListaSolicitudServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlListaStockProducto {
            get {
                return this.XmlListaStockProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlListaStockProductoField, value) != true)) {
                    this.XmlListaStockProductoField = value;
                    this.RaisePropertyChanged("XmlListaStockProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPerfilUsuario {
            get {
                return this.XmlPerfilUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPerfilUsuarioField, value) != true)) {
                    this.XmlPerfilUsuarioField = value;
                    this.RaisePropertyChanged("XmlPerfilUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlProducto {
            get {
                return this.XmlProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlProductoField, value) != true)) {
                    this.XmlProductoField = value;
                    this.RaisePropertyChanged("XmlProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlSolicitudServicio {
            get {
                return this.XmlSolicitudServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlSolicitudServicioField, value) != true)) {
                    this.XmlSolicitudServicioField = value;
                    this.RaisePropertyChanged("XmlSolicitudServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlStockProducto {
            get {
                return this.XmlStockProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlStockProductoField, value) != true)) {
                    this.XmlStockProductoField = value;
                    this.RaisePropertyChanged("XmlStockProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioValidarLogin.IServicioValidarLogin")]
    public interface IServicioValidarLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValidarLogin/ValidarLoginEscritorio", ReplyAction="http://tempuri.org/IServicioValidarLogin/ValidarLoginEscritorioResponse")]
        BuenosAires.VentaBA.ServicioValidarLogin.Respuesta ValidarLoginEscritorio(string cuenta, string password, string tipousu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioValidarLogin/ValidarLoginEscritorio", ReplyAction="http://tempuri.org/IServicioValidarLogin/ValidarLoginEscritorioResponse")]
        System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioValidarLogin.Respuesta> ValidarLoginEscritorioAsync(string cuenta, string password, string tipousu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioValidarLoginChannel : BuenosAires.VentaBA.ServicioValidarLogin.IServicioValidarLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioValidarLoginClient : System.ServiceModel.ClientBase<BuenosAires.VentaBA.ServicioValidarLogin.IServicioValidarLogin>, BuenosAires.VentaBA.ServicioValidarLogin.IServicioValidarLogin {
        
        public ServicioValidarLoginClient() {
        }
        
        public ServicioValidarLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioValidarLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioValidarLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioValidarLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.VentaBA.ServicioValidarLogin.Respuesta ValidarLoginEscritorio(string cuenta, string password, string tipousu) {
            return base.Channel.ValidarLoginEscritorio(cuenta, password, tipousu);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.VentaBA.ServicioValidarLogin.Respuesta> ValidarLoginEscritorioAsync(string cuenta, string password, string tipousu) {
            return base.Channel.ValidarLoginEscritorioAsync(cuenta, password, tipousu);
        }
    }
}
