# Generated by Django 4.2.1 on 2023-06-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipousu',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Técnico', 'Técnico'), ('Vendedor', 'Vendedor'), ('Bodeguero', 'Bodeguero'), ('Contador', 'Contador'), ('Administrador', 'Administrador'), ('Superusuario', 'Superusuario')], max_length=50),
        ),
    ]
