SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (OBJECT_ID('SP_ESTADO_DESPACHADO_GUIA_DE_DESPACHO', 'P') IS NOT NULL) DROP PROCEDURE SP_ESTADO_DESPACHADO_GUIA_DE_DESPACHO
GO
CREATE PROCEDURE SP_ESTADO_DESPACHADO_GUIA_DE_DESPACHO
    @nro VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

    Update GuiaDespacho
    Set estadogd = 'Despachado'
    where nrogd = @nro;
END
GO