SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (OBJECT_ID('SP_MODIFICAR_ESTADO_GUIA_DE_DESPACHO', 'P') IS NOT NULL) DROP PROCEDURE SP_MODIFICAR_ESTADO_GUIA_DE_DESPACHO
GO
CREATE PROCEDURE SP_MODIFICAR_ESTADO_GUIA_DE_DESPACHO
    @nro VARCHAR(50),
    @estado VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

    Update GuiaDespacho
    Set estadogd = @estado
    where nrogd = @nro;
END
GO