SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (OBJECT_ID('SP_OBTENER_PRODUCTOS', 'P') IS NOT NULL) DROP PROCEDURE SP_OBTENER_PRODUCTOS
GO
CREATE PROCEDURE SP_OBTENER_PRODUCTOS 
AS
BEGIN
	SET NOCOUNT ON;

	SELECT * FROM Producto

END
GO