SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (OBJECT_ID('SP_RESERVAR_EQUIPO_ANWO', 'P') IS NOT NULL) DROP PROCEDURE SP_RESERVAR_EQUIPO_ANWO
GO
CREATE PROCEDURE SP_RESERVAR_EQUIPO_ANWO
    @nroserie VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;

    Update AnwoListaProducto
    Set reservadoba = CASE WHEN reservadoba = 'N' THEN 'S' ELSE 'N' END
    where nroserieanwo = @nroserie;
END
GO